ball_collisions.pdf: ball_collisions.tex $(wildcard *.eps) $(wildcard *.cls)
	latex ball_collisions.tex
	latex ball_collisions.tex
	latex ball_collisions.tex
	dvips ball_collisions.dvi
	ps2pdf ball_collisions.ps