#!/perl5/perl -w

# this is used to generate an install-script for
# the meshes (binary-version). if you have the sources and make installed, just type 'make'

open (INSTALL_SCRIPT, ">install.bat") || die "can't open install.bat for writing!: $!\n";

print INSTALL_SCRIPT "rem generated by $0\n";

while (defined($som_file = <*.som>)) {
    $som_file_temp = $som_file;
    $som_file_temp =~ tr/A-Z/a-z/;
    $idx = index($som_file_temp, ".som");
    $xyz_file = $som_file;
    substr($xyz_file, $idx, 4) = ".xyz";
    print INSTALL_SCRIPT "if exist $xyz_file del $xyz_file\nsom2xyz $som_file $xyz_file\n";
}

while (defined($id_file = <*.id>)) {
    $id_file_temp = $id_file;
    $id_file_temp =~ tr/A-Z/a-z/;
    $idx = index($id_file_temp, ".id");
    $wld_file = $id_file;
    substr($wld_file, $idx, 3) = ".wld";
    print INSTALL_SCRIPT "if exist $wld_file del $wld_file\nplaygod $id_file $wld_file\n";
}

print INSTALL_SCRIPT "\@echo Installation finished.\n";
print INSTALL_SCRIPT "\@echo Please switch to full-screen-mode (Alt+Enter)\n";
print INSTALL_SCRIPT "\@echo and start xpos using xpos [world-file]\n";
print INSTALL_SCRIPT "\@echo i.e. try 'xpos simple.wld'.\n";
print INSTALL_SCRIPT "\@echo or to run all: 'for %I in (*.wld) do xpos %I'.\n";
print INSTALL_SCRIPT "\@echo READ README.HTM. IT CONTAINS IMPORTANT INFORMATION\n";

close (INSTALL_SCRIPT);

